return function () 
    local configs = require("nvim-treesitter.configs")
    configs.setup({
        ensure_installed = {
            "bash",
            "c",
            "cpp",
            "css",
            "dart",
            "diff",
            "dockerfile",
            "go",
            "gomod",
            "html",
            "javascript",
            "json",
            "lua",
            "norg",
            "nginx",
            "regex",
            "sql",
            "sway",
            "terraform",
            "typst",
            "udev",
            "zathurarc",
            "zig",
            "make",
            "norg",
            "python",
            "rust",
            "svelte",
            "toml",
            "tsx",
            "typescript",
        },
        -- ignore_install = { "markdown", "latex" },
        ignore_install = { "latex" },
        sync_install = true,
        highlight = {
            enable = true,
            additional_vim_regex_highlighting = false,
            disable = { "latex" },
        },
        indent = { enable = true },  
    })
end
